spring.application.name: better-reads-datat-loader

datadump.location:
    author: E:/Chan/Projects_02/betterreads_data_loader/better-reads-data-loader/src/main/resources/test-authors.txt
    works: E:/Chan/Projects_02/betterreads_data_loader/better-reads-data-loader/src/main/resources/test-works.txt

spring:
    output:
        ansi:
          enabled: always 
    cassandra: 
        keyspace-name: main 
        username: SuLJwUMDUYxxeCoMgHIvTQWp 
        password: qOEMyzBuNU+T9HLlpekR0nsntyl+aW5cg1R877b4Sy6hOj_JvAtg16zpbf-uo,IZOY5jcSPNAw+_MjuXM6T.K2zLuG4g-1aI3Km7CqCb3ksHrNf+DrpZ4i7uLyWLmH4B
        schema-action: create-if-not-exists
        request:
            timeout: 10s
        connection:
            connect-timeout: 10s
            init-query-timeout: 10s
    main.allow-circular-references: true

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: 1ba3e572-9148-48d9-bb28-c4ee3dd9f775-1
    region: asia-south1
    keyspace: main
    application.token: AstraCS:SuLJwUMDUYxxeCoMgHIvTQWp:ae644b24e3dd06c8e93c01b4d21b648caae7815ee817a7280813b44d5d461584     
              

